### ISSUE TITLE
ISSUE : 그룹원 삭제 기능 시 DB 처리

### ISSUE THREAD

**Issue by seohee99** [seohee99/MM-Care#20]
그룹원을 그룹에 초대할 때 초대 링크를 보낸 경우, 
1. GROUP_JOIN 테이블에 해당 사용자를 추가하되, join_activate 컬럼을 0으로 한다.
2. 사용자가 초대에 응할 경우 join_activate를 1로 업데이트한다.

이 순서로 그룹과 사용자를 연결하는 방식이어서 join_activate 컬럼을 만들었었습니다.

<br>
<br>

반대로 그룹원을 그룹에서 삭제할 경우
1. join_activate 컬럼을 다시 0으로 업데이트 한다.(GROUP_JOIN테이블에 사용자 데이터는 남아있는 형태)
2. GROUP_JOIN 테이블에서 사용자를 삭제한다.

이 두 가지의  방법이 있을 것 같은데 어떤 방식이 더 효율적일까요?

**Comment by sjsin0905** [comment]
제 생각에는 말이죠,,, seohee99님이 말씀하신 방법 둘 다 좋은 방법입니다만,,,

사용자를 추가할 때 먼저 사용자의 튜플이 이미 존재하는지 체크를 하는 로직이 존재하는 경우 1번을 선택하는것이 효율적인것 같아요! 

그리고 요즘은 모든 기록들이 데이터가 되는 시대이기 때문에 삭제를 하는 방향 보다는 기록을 남기는 방향이 더 나은 방법 같다는 개인적인 생각입니다 :)

답변이 도움이 되셨나요? 좋은 질문으로 저도 한 번 다시 생각해보게 되는 좋은 기회였습니다 >_<
